language: python
python:
  - "3.7.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - python -m pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)